Vehicles: [306]
simTime: 99
runNo: 1
noIBE: true
Numerology: 0
ChannelBW: [25]
SubChannel: 25
seed: 1
Periodic: true
RSRP: -120.24
mcs: 16
PDB: 100
pkeep: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99]
sumo_on: true
tracefile: ["data_lights"]