Vehicles:
  - _val: 175
    tracefile: ["data_traffic_light_small"]
  - _val: 350
    tracefile: ["data_traffic_light_medium"]
  - _val: 500
    tracefile: ["data_traffic_light_big"]
  - _val: 700
    tracefile: ["data_traffic_light_large", "data_2_traffic_lights_large", "data_baseline_large"]
simTime: 99
runNo: 1
noIBE: true
Numerology: 0
ChannelBW: [25]
SubChannel: 25
seed: 1
Periodic: true
RSRP: -120.24
mcs: 16
PDB: 100
pkeep: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99]
sumo_on: true